name: testapplication
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^5.7.2+3
  flutter_svg: ^2.0.7
  dio:
  google_fonts: ^5.1.0
  http:
  rx_shared_preferences: ^3.0.0
  modal_bottom_sheet: ^3.0.0-pre
  another_flushbar: ^1.12.30
  in_app_review:
  onesignal_flutter: ^5.0.0
  getwidget: ^4.0.0
  firebase_core: ^2.15.1
  firebase_remote_config: ^4.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

